var GRAVITY = 700;
var MAN_WEIGHT = 65;
var GIRL_WEIGHT = 45;

var WALL_THICKNESS = 50;

var COLBRIDE = 1;
var COLBAG = 2;
var COLGROOM = 3;
var COLPLAYER = 5;
var COLITEM = 6;

var COLROPEPOINTER = 7;